config/routes.rb
Store::Application.routes.draw do
  get "users/new"

  get "welcome/home"
  get "welcome/thank_you"
  get "welcome/register"
  resources :smartphones
  resources :users
  resources :sessions
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

  root :to => "welcome", :action => "home"

end

app/models/smartphone.rb
class Smartphone < ActiveRecord::Base
  belongs_to :user
  def self.search(search_query)
    if search_query
      find(:all, :conditions => ['name LIKE ?', "%#{ search_query}%"])
    else
      find(:all)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery

protected
# Returns the currently logged in user or nil if there isn't one
def current_user
return unless session[:user_id]
@current_user ||= User.find_by_id(session[:user_id])
end
# Make current_user available in templates as a helper
helper_method :current_user
# Filter method to enforce a login requirement
# Apply as a before_filter on any controller you want to protect
def authenticate
logged_in? ? true : access_denied
end
# Predicate method to test for a logged in user
def logged_in?
current_user.is_a? User
end
# Make logged_in? available in templates as a helper
helper_method :logged_in?
def access_denied
redirect_to login_path, :notice => "Please log in to continue" and return false
end
end

app/controllers/smartphones_controller.rb
class SmartphonesController < ApplicationController
  # GET /smartphones
  # GET /smartphones.xml
  before_filter :authenticate, :except => [:index, :show]
  def index
    @smartphones = Smartphone.search(params[:search_query])

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @smartphones }
    end
  end

  # GET /smartphones/1
  # GET /smartphones/1.xml
  def show
    @smartphone = Smartphone.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @smartphone }
    end
  end

  # GET /smartphones/new
  # GET /smartphones/new.xml
  def new
    @smartphone = Smartphone.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @smartphone }
    end
  end

  # GET /smartphones/1/edit
  def edit
    @smartphone = Smartphone.find(params[:id])
  end

  # POST /smartphones
  # POST /smartphones.xml
  def create
    @smartphone = current_user.smartphones.new(params[:smartphone])

    respond_to do |format|
      if @smartphone.save
        format.html { redirect_to(@smartphone, :notice => 'Smartphone was successfully created.') }
        format.xml { render :xml => @smartphone, :status => :created, :location => @smartphone }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @smartphone.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /smartphones/1
  # PUT /smartphones/1.xml
  def update
    @smartphone = Smartphone.find(params[:id])

    respond_to do |format|
      if @smartphone.update_attributes(params[:smartphone])
        format.html { redirect_to(@smartphone, :notice => 'Smartphone was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @smartphone.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /smartphones/1
  # DELETE /smartphones/1.xml
  def destroy
    @smartphone = Smartphone.find(params[:id])
    @smartphone.destroy

    respond_to do |format|
      format.html { redirect_to(smartphones_url) }
      format.xml { head :ok }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def thank_you
  end

  def register
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/smartphones_helper.rb
module SmartphonesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
| <%= link_to "Phone Catalogue", smartphones_path %> |
<%= link_to "Leave Site", :controller => "welcome", :action => "thank_you" %> |
<%= link_to "Register", :controller => "welcome", :action => "register" %> |
<%= link_to "Home", :controller => "welcome", :action => "home" %> |
<%= link_to "Create User", new_user_path %> |
<%= link_to "Login", login_path %> |
<%= link_to "Logout", logout_path %>

<div id='header'>
<% if logged_in? %>
<%= current_user.email %> |
<%= link_to 'Logout', logout_path %> |
<%= link_to "Create User", new_user_path %> |
<% else %>
<%= link_to "Login", login_path %> |
<% end %>
</div>

<%= yield %>

</body>
</html>

app/views/smartphones/_form.html.erb
<%= form_for(@smartphone) do |f| %>
    <% if @smartphone.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@smartphone.errors.count, "error") %> prohibited this smartphone from being saved:</h2>

          <ul>
            <% @smartphone.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :phone %>
      <br/>
      <%= f.text_field :phone %>
    </div>
    <div class="field">
      <%= f.label :description %>
      <br/>
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <%= f.label :image_url %>
      <br/>
      <%= f.text_field :image_url %>
    </div>
    <div class="field">
      <%= f.label :price %>
      <br/>
      <%= f.text_field :price %>
    </div>
    <div class="field">
      <%= f.label :techspec %>
      <br/>
      <%= f.text_area :techspec %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/smartphones/edit.html.erb
<h1>Editing smartphone</h1>

<%= render 'form' %>

<%= link_to 'Show', @smartphone %> |
<%= link_to 'Back', smartphones_path %>

app/views/smartphones/index.html.erb
<div id="smartphone_list">
<h1>Listing smartphones</h1>
<th>UserID</th>
<table>
  <% @smartphones.each do|smartphone| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

        <td>
          <%= image_tag(smartphone.image_url, :class => 'list_image') %>
          </td>

        <td class="list_description">
          <dl>
            <dt><%= smartphone.phone %></dt>
            <dd><%= truncate(strip_tags(smartphone.description),
            :length => 80) %></dd>
            </dl>
          </td>

        <td class="list actions">

        <%= link_to 'Show', smartphone %><br/>
        <%= link_to 'Edit', edit_smartphone_path(smartphone) %><br/>
        <%= link_to 'Destroy', smartphone,
                    :confirm => 'Are you sure?',
                    :method => :delete %>
        </td>
      </tr>
  <% end %>
</table>
</div>

<br/>

<%= link_to 'New Smartphone', new_smartphone_path %>

app/views/smartphones/new.html.erb
<h1>New smartphone</h1>

<%= render 'form' %>

<%= link_to 'Back', smartphones_path %>

app/views/smartphones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Phone:</b>
  <%= @smartphone.phone %>
</p>

<p>
  <b>Description:</b>
  <%= @smartphone.description %>
</p>

<p>
  <b>Image url:</b>
  <%= @smartphone.image_url %>
</p>

<p>
  <b>Price:</b>
  <%= @smartphone.price %>
</p>

<p>
  <b>Techspec:</b>
  <%= @smartphone.techspec %>
</p>


<%= link_to 'Edit', edit_smartphone_path(@smartphone) %> |
<%= link_to 'Back', smartphones_path %>

app/views/welcome/home.html.erb
<h1>Welcome to my Homepage</h1>
<p> Workshop1 </p>

app/views/welcome/register.html.erb
<h1>Register</h1>
<div class="field">
  <%= label_tag :email %>
  <br/>
  <%= text_field_tag :email %>
  <br/>
  <%= label_tag :password %>
  <br/>
  <%= password_field_tag :password %>
</div>

app/views/welcome/thank_you.html.erb
<h1>Thanks for visiting!!</h1>